x32: Generate 0x67 prefix for VSIB address if needed
Dword indices in VSIB address are sign-extended to 64 bits.  In x32, add
ADDR_PREFIX_OPCODE prefix for VSIB address of Dword indices without base
register nor symbol so that Dword indices will be zero-extended to 64 bits
unless -moperand-check=none is passed to assembler.

We can't have ADDR_PREFIX_OPCODE prefix with 32-bit address if there is
segment override since address will be

segment base + zero-extend(base + index * scale + disp)

instead of

zero-extend (segment base + base + index * scale + disp)

The address will be wrong if (base + index * scale + disp) is negative.
But GCC:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89502

may generate

	movl	$24, %edx
	movl	%fs:(%edx), %ecx

instead of

	movl	%fs:24, %ecx

So a warning:

Warning: segment `%fs' override with 32-bit address

is issued by default.  -moperand-check=error will turn a warning into
an error.

Error: segment `%fs' override with 32-bit address

gas/

	PR gas/24263
	* config/tc-i386.c (output_insn): In x32, add 0x67 address size
	prefix for VSIB address of Dword indices without base register nor
	symbol.  Issue a warning or an error for segment override with
	ADDR_PREFIX_OPCODE prefix.
	* testsuite/gas/i386/ilp32/ilp32.exp: Run x86-64-seg-inval.
	* testsuite/gas/i386/ilp32/x86-64-seg-inval.l: New file.
	* testsuite/gas/i386/ilp32/x86-64-seg-inval.s: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg-none.d: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg-none.s: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg-warn.d: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg-warn.s: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg.d: Likewise.
	* testsuite/gas/i386/ilp32/x86-64-seg.s: Likewise.

opcodes/

	PR gas/24263
	* i386-gen.c (opcode_modifiers): Add VecSIBQword.
	* i386-opc.h (VecSIBQword): New.
	(i386_opcode_modifier): Add vecsibqword.
	* i386-opc.tbl: Add VecSIBQword to VSIB instructions with Qword
	indices.
	* i386-tbl.h: Regenerated.