dwarf: Bail out for linker input file
find_abstract_instance may work only with relocated files.  When it is
called by linker to find the the nearest line, debug info may not have
been relocated yet.  When it happens, linker should bail out instead of
issuing an error.  For the testcase at

https://sourceware.org/bugzilla/show_bug.cgi?id=23425#c1

now we get

$ ./ld ccELcIbzdebugobjtem cccLlhS9debugobjtem ccqD9BbN.ltrans0.ltrans.o
./ld: warning: cannot find entry symbol _start; defaulting to 0000000000401000
./ld: ccqD9BbN.ltrans0.ltrans.o: in function `strerrno(int)':
/abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:16: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:22: undefined reference to `strerrno_s(char*, unsigned long, int)'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:25: undefined reference to `std::string::operator=(char const*)'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:27: undefined reference to `std::string::operator+=(char const*)'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:31: undefined reference to `std::string::operator=(char const*)'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:34: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
./ld: /abuild/rguenther/obj-sccvn-g/gcc/cpputil.cpp:34: undefined reference to `_Unwind_Resume'
./ld: ccqD9BbN.ltrans0.ltrans.o:(.eh_frame+0x4b): undefined reference to `__gcc_personality_v0'
$

bfd/

	PR ld/23425
	* bfd.c (bfd): Extend flags to 21 bits.
	(BFD_LINKER_INPUT): New.
	* bfd-in2.h: Regenerated.
	* dwarf2.c (find_abstract_instance): Bail out for linker input
	file.

ld/

	PR ld/23425
	* ldmisc.c (vfinfo): Set BFD_LINKER_INPUT in linker input file
	before calling bfd_find_nearest_line.